# Generated by Django 3.1.7 on 2021-05-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='user_phone',
        ),
    ]
